import "./testFileTimeout.mjs";
import assert from "node:assert";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
const here = path.dirname(new URL(import.meta.url).pathname);
const root = await fs.mkdtemp(path.join(os.tmpdir(), "other-exporters-mutation-"));
const copy = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), "other-exporters-mutation-copy-")));
const helper = await fs.readFile(path.join(here, "vault-scripts/export-json-atomic.mjs"), "utf8");
const needle = "    await fs.rename(tempPath, filePath);";
assert.ok(helper.includes(needle), "mutation anchor must be executable atomic rename");
await fs.writeFile(path.join(copy, "export-json-atomic.mjs"), helper.replace(needle, "    await fs.writeFile(filePath, \"\");\n    for (let start = 0; start < json.length; start += 64) { await fs.appendFile(filePath, json.slice(start, start + 64)); await sleep(10); }"));
const source = await fs.readFile(path.join(here, "vault-scripts/export-ops-map.mjs"), "utf8"); await fs.writeFile(path.join(copy, "export-ops-map.mjs"), source);
const vault = path.join(root, "vault"), out = path.join(vault, "Operations", "ops-map.json");
const run = () => new Promise((resolve) => { const child = spawn(process.execPath, [path.join(copy, "export-ops-map.mjs"), vault], { env: { ...process.env, AIOS_EXPORT_TEST_WRITE_CHUNK_DELAY_MS: "20" }, stdio: ["ignore", "pipe", "pipe"] }); let stderr = ""; child.stderr.on("data", d => stderr += d); child.once("exit", code => resolve({ code, stderr })); });
let invalid = false, polling = true, reads = 0;
const reader = (async () => { while (polling) { try { reads++; JSON.parse(await fs.readFile(out, "utf8")); } catch (error) { if (error?.code !== "ENOENT") invalid = true; } await new Promise((r) => setTimeout(r, 1)); } })();
const results = await Promise.all(Array.from({ length: 3 }, run)); polling = false; assert.deepEqual(results.map((r) => r.code), [0, 0, 0], JSON.stringify(results)); await reader;
await fs.rm(root, { recursive: true, force: true });
await fs.rm(copy, { recursive: true, force: true });
assert.equal(invalid, true, "MUTATION CHECK other exporters: replacing atomic rename with direct live write must expose invalid JSON to a concurrent reader");
console.log("MUTATION (atomic rename removed): concurrent reader observed invalid live JSON.");
